{
  "contract": "0x50f0557ae11d55829949bf7af8cd9f69b80a56eb",
  "tool": "mythril",
  "start": 1563303338.9550238,
  "end": 1563303366.0059538,
  "duration": 27.05093002319336,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 733,
        "code": "balance of the specified address.\n  * @param",
        "debug": "The exception is triggered under the following conditions:\n\ncalldatasize_StandardToken: 0x4\ncalldata_StandardToken_0: 0x95ea7b300000000000000000000000000000000000000000000000000000000\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_contracts/0x50f0557ae11d55829949bf7af8cd9f69b80a56eb.sol",
        "function": "approve(address,uint256)",
        "lineno": 506,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 1156,
        "code": "balance of the specified address.\n  * @param",
        "debug": "The exception is triggered under the following conditions:\n\ncalldatasize_StandardToken: 0x4\ncalldata_StandardToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_contracts/0x50f0557ae11d55829949bf7af8cd9f69b80a56eb.sol",
        "function": "transferFrom(address,address,uint256)",
        "lineno": 506,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 1940,
        "code": "balance of the specified address.\n  * @param",
        "debug": "The exception is triggered under the following conditions:\n\ncalldatasize_StandardToken: 0x4\ncalldata_StandardToken_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_contracts/0x50f0557ae11d55829949bf7af8cd9f69b80a56eb.sol",
        "function": "transfer(address,uint256)",
        "lineno": 506,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 2492,
        "code": "   ow",
        "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_StandardToken_4: 0x9c9efb7ae5acd378025256a3945f5859076e809243093d9ecae2636c9fd28979\ncalldata_StandardToken_32 + 4: 0xc290137095b13347e55005a6dc184559e0489f1233480050d0fb4bba17d34179\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xc290137095b13347e55005a6dc184559e0489f1233480050d0fb4bba17d34179\ncalldata_StandardToken_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_StandardToken: 0x44\ncallvalue: 0x0\n",
        "description": "A possible integer overflow exists in the function `transfer(address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_contracts/0x50f0557ae11d55829949bf7af8cd9f69b80a56eb.sol",
        "function": "transfer(address,uint256)",
        "lineno": 249,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 2505,
        "code": "sg.sender;\n  }",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_StandardToken_4: 0xbd5dfeabad0efffffffffeffffffffffd599ffefbfe6f24271e80e64322c0700\ncalldata_StandardToken_32 + 4: 0x6218000d800000000000000000000000039800002005500633e06f771baff7fc\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x6218000d800000000000000000000000039800002005500633e06f771baff7fc\ncalldata_StandardToken_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_StandardToken: 0x44\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_contracts/0x50f0557ae11d55829949bf7af8cd9f69b80a56eb.sol",
        "function": "transfer(address,uint256)",
        "lineno": 249,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 2529,
        "code": "\n   * @dev The",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\ncalldata_StandardToken_32 + 4: 0x1\ncalldata_StandardToken_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_StandardToken: 0x44\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_contracts/0x50f0557ae11d55829949bf7af8cd9f69b80a56eb.sol",
        "function": "transfer(address,uint256)",
        "lineno": 244,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}