{"error": null, "issues": [{"address": 2985, "code": "ring the contract ownership", "debug": "The exception is triggered under the following conditions:\n\nstorage_7: 0x0\ncaller: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_Z1Coin_0: 0x1608f18f00000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "disableTransfers(bool)", "lineno": 89, "title": "Exception state", "type": "Informational"}, {"address": 3053, "code": "      @dev anyone who fi", "debug": "The exception is triggered under the following conditions:\n\nstorage_10: 0x0\ncalldata_Z1Coin_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "transferFrom(address,address,uint256)", "lineno": 359, "title": "Exception state", "type": "Informational"}, {"address": 3392, "code": "ring the contract ownership", "debug": "The exception is triggered under the following conditions:\n\nstorage_7: 0x0\ncaller: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_Z1Coin_0: 0x3261937500000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "ChangeMiningReward(uint256)", "lineno": 89, "title": "Exception state", "type": "Informational"}, {"address": 3862, "code": "ring the contract ownership", "debug": "The exception is triggered under the following conditions:\n\nstorage_7: 0x0\ncaller: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_Z1Coin_0: 0x5e35359e00000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "_function_0x5e35359e", "lineno": 89, "title": "Exception state", "type": "Informational"}, {"address": 4167, "code": "emits automatically generated", "debug": "", "description": "This contract executes a message call to an address provided as a function argument. Generally, it is not recommended to call user-supplied addresses using Solidity's call() construct. Note that attackers might leverage reentrancy attacks to exploit race conditions or manipulate this contract's state.", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "_function_0x5e35359e", "lineno": 172, "title": "Message call to external contract", "type": "Warning"}, {"address": 4829, "code": "ring the contract ownership", "debug": "The exception is triggered under the following conditions:\n\nstorage_7: 0x0\ncaller: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_Z1Coin_0: 0x867904b400000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "issue(address,uint256)", "lineno": 89, "title": "Exception state", "type": "Informational"}, {"address": 5533, "code": "ring the contract ownership", "debug": "The exception is triggered under the following conditions:\n\nstorage_7: 0x0\ncaller: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_Z1Coin_0: 0xa24835d100000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "destroy(address,uint256)", "lineno": 89, "title": "Exception state", "type": "Informational"}, {"address": 5877, "code": "      @dev anyone who fi", "debug": "The exception is triggered under the following conditions:\n\nstorage_10: 0x0\ncalldata_Z1Coin_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "transfer(address,uint256)", "lineno": 359, "title": "Exception state", "type": "Informational"}, {"address": 7489, "code": "rt(z >=", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Z1Coin_32_+_4: 0xc050fffff320c00020003d81af848540000000000000040000110001bd062022\ncalldata_Z1Coin_32 + 36: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Z1Coin_4: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\ncalldata_Z1Coin_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_Z1Coin_4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_10: 0xff00\ncalldata_Z1Coin_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "transferFrom(address,address,uint256)", "lineno": 23, "title": "Integer Overflow ", "type": "Warning"}, {"address": 7502, "code": "   return z;\n  ", "debug": "The exception is triggered under the following conditions:\n\nstorage_4: 0x1\ncalldata_Z1Coin_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_Z1Coin_4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_7: 0x0\ncaller: 0x0\ncalldata_Z1Coin_0: 0x867904b400000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "issue(address,uint256)", "lineno": 24, "title": "Exception state", "type": "Informational"}, {"address": 7526, "code": " - _y;\n    }\n\n  ", "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\ncalldata_Z1Coin_32 + 36: 0x1\ncalldata_Z1Coin_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\ncalldata_Z1Coin_4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_10: 0xff00\ncalldata_Z1Coin_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_Z1Coin: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/35/0xc1d813fa26f04035b73e3770ed18ba5ecef3e17f.sol", "function": "transferFrom(address,address,uint256)", "lineno": 37, "title": "Exception state", "type": "Informational"}], "success": true}