{
  "contract": "0x3c83129d5eb5df2006c9b3d39841bd3a2bb6ebfd",
  "tool": "mythril",
  "start": 1563612947.231454,
  "end": 1563613361.1710784,
  "duration": 413.9396245479584,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 4283,
        "code": "      uint sum =",
        "debug": "calldata_Token_4: 0x814019176a8009a2d1838bab6ccbcf75689d980082e74445757a64185b33d52a\nstorage_3: 0x0\ncaller: 0x0\ncalldata_Token_0: 0x6737b31e00000000000000000000000000000000000000000000000000000000\ncalldatasize_Token: 0x4\ncallvalue: 0x0\n",
        "description": "A possible integer overflow exists in the function `repayment(uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_chucks/22/0x3c83129d5eb5df2006c9b3d39841bd3a2bb6ebfd.sol",
        "function": "repayment(uint256)",
        "lineno": 213,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 4301,
        "code": ";\n\nlibrary SafeMat",
        "debug": "storage_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_Token_4: 0x3e8\nstorage_3: 0x0\ncaller: 0x0\ncalldata_Token_0: 0x6737b31e00000000000000000000000000000000000000000000000000000000\ncalldatasize_Token: 0x4\ncallvalue: 0x0\n",
        "description": "A possible integer overflow exists in the function `repayment(uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_chucks/22/0x3c83129d5eb5df2006c9b3d39841bd3a2bb6ebfd.sol",
        "function": "repayment(uint256)",
        "lineno": 1,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 4893,
        "code": "int amount) onlyOwner {\n   ",
        "debug": "The exception is triggered under the following conditions:\n\ncalldata_Token_4: 0x0\nstorage_4: 0x0\ncalldata_Token_0: 0xa85f376100000000000000000000000000000000000000000000000000000000\ncalldatasize_Token: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/22/0x3c83129d5eb5df2006c9b3d39841bd3a2bb6ebfd.sol",
        "function": "_function_0xa85f3761",
        "lineno": 203,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 5002,
        "code": "quire(amount >= 1000);\n\n        repayments.p",
        "debug": "The exception is triggered under the following conditions:\n\ncalldata_Token_32 + 4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\ncalldata_Token_4: 0x0\ncalldata_Token_0: 0xb933ceac00000000000000000000000000000000000000000000000000000000\ncalldatasize_Token: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/22/0x3c83129d5eb5df2006c9b3d39841bd3a2bb6ebfd.sol",
        "function": "_function_0xb933ceac",
        "lineno": 204,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 6422,
        "code": "\n            if(sum > 0) {\n                totalSupply = t",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_4: 0xdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_Token_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_Token: 0x4\nstorage_2 +\n62514009886607029107290561805838585334079798074568712924583230797734656856478 +\n3*\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Token_4: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Token_4: 0x0\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/22/0x3c83129d5eb5df2006c9b3d39841bd3a2bb6ebfd.sol",
        "function": "transferFrom(address,address,uint256)",
        "lineno": 219,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 7684,
        "code": "t(c >",
        "debug": "calldata_Token_32 + 4: 0x57f25cd000000000000000000000000000000000000000000000000000000000\nstorage_0: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\nstorage_6: 0x0\nstorage_3: 0x0\ncaller: 0x0\ncalldata_Token_0: 0x40c10f1900000000000000000000000000000000000000000000000000000000\ncalldatasize_Token: 0x4\ncallvalue: 0x0\n",
        "description": "A possible integer overflow exists in the function `mint(address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_chucks/22/0x3c83129d5eb5df2006c9b3d39841bd3a2bb6ebfd.sol",
        "function": "mint(address,uint256)",
        "lineno": 22,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 7697,
        "code": "   return c;\n ",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_0: 0x1\ncalldata_Token_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_6: 0x0\nstorage_3: 0x0\ncaller: 0x0\ncalldata_Token_0: 0x40c10f1900000000000000000000000000000000000000000000000000000000\ncalldatasize_Token: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/22/0x3c83129d5eb5df2006c9b3d39841bd3a2bb6ebfd.sol",
        "function": "mint(address,uint256)",
        "lineno": 23,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 7721,
        "code": "\n        retur",
        "debug": "The exception is triggered under the following conditions:\n\ncalldata_Token_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncalldata_Token_0: 0x42966c6800000000000000000000000000000000000000000000000000000000\ncalldatasize_Token: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/22/0x3c83129d5eb5df2006c9b3d39841bd3a2bb6ebfd.sol",
        "function": "burn(uint256)",
        "lineno": 16,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}