{"error": null, "issues": [{"address": 5074, "code": "\n\n /*", "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_TelomereToken_32_+_4: 0xc050fffff320c00020003d81af848540000000000000040000110001bd062022\ncalldata_TelomereToken_32 + 36: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_TelomereToken_4: 0xfe51000008ce80008001c1d33616877ffffffffffffff7ffffe10000398d50ac\ncalldata_TelomereToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_3: 0x0\ncalldata_TelomereToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_TelomereToken: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/7/0xc239b871cbf9c60f022676700663c552a086717d.sol", "function": "transferFrom(address,address,uint256)", "lineno": 51, "title": "Integer Overflow ", "type": "Warning"}, {"address": 5087, "code": "itle Ownable\n ", "debug": "The exception is triggered under the following conditions:\n\nstorage_1: 0x1\ncalldata_TelomereToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_TelomereToken_0: 0x40c10f1900000000000000000000000000000000000000000000000000000000\ncalldatasize_TelomereToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/7/0xc239b871cbf9c60f022676700663c552a086717d.sol", "function": "mint(address,uint256)", "lineno": 54, "title": "Exception state", "type": "Informational"}, {"address": 7991, "code": "\n  /**\n  * @de", "debug": "The exception is triggered under the following conditions:\n\ncalldata_TelomereToken_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_1: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_TelomereToken_0: 0x42966c6800000000000000000000000000000000000000000000000000000000\ncalldatasize_TelomereToken: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/7/0xc239b871cbf9c60f022676700663c552a086717d.sol", "function": "burn(uint256)", "lineno": 42, "title": "Exception state", "type": "Informational"}], "success": true}