{"error": null, "issues": [{"address": 648, "code": " YOU WIN,THIS CONT", "debug": "storage_3: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncallvalue: 0x0\ncalldata_Lottery50chance_4: 0x0\nstorage_1: 0x0\ncalldata_Lottery50chance_0: 0x6898f82b00000000000000000000000000000000000000000000000000000000\ncalldatasize_Lottery50chance: 0x4\n", "description": "A possible integer overflow exists in the function `play(uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/38/0x29d6cf436c893c7e44ea926411d5fd4dd763d9b3.sol", "function": "play(uint256)", "lineno": 2, "title": "Integer Overflow ", "type": "Warning"}, {"address": 918, "code": "c log;\n\n  modifier onlyO", "debug": "The exception is triggered under the following conditions:\n\ncalldata_Lottery50chance_4: 0x0\nstorage_3: 0x0\ncalldata_Lottery50chance_0: 0xf82c50f100000000000000000000000000000000000000000000000000000000\ncalldatasize_Lottery50chance: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/38/0x29d6cf436c893c7e44ea926411d5fd4dd763d9b3.sol", "function": "_function_0xf82c50f1", "lineno": 20, "title": "Exception state", "type": "Informational"}], "success": true}