{"error": null, "issues": [{"address": 4933, "code": " public d", "debug": "storage_8: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_14: 0xff00\nstorage_4: 0x0\nstorage_3: 0xffffffffffffffffffffffffffffffffffffffff00\ncaller: 0x0\ncalldata_Target_0: 0x180da45000000000000000000000000000000000000000000000000000000000\ncalldatasize_Target: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `addTierRateAndTokens(uint256,uint256,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_contracts/0xea58183f57d2f3ee111290164e83d39429b629b1.sol", "function": "addTierRateAndTokens(uint256,uint256,uint256)", "lineno": 241, "title": "Integer Overflow ", "type": "Warning"}, {"address": 12934, "code": "alanc", "debug": "storage_8: 0x7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_9: 0x93bbb3bbb3bbbb8773f3310a622c8f2108628c204c2000000000000000887485\ncalldata_Target_32 + 4: 0x9088908890888879c80bd287c0118f60fa80800006a298000000000002837595\nstorage_14: 0xff00\nstorage_4: 0x0\nstorage_3: 0xffffffffffffffffffffffffffffffffffffffff00\ncaller: 0x0\ncalldata_Target_0: 0x180da45000000000000000000000000000000000000000000000000000000000\ncalldatasize_Target: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `addTierRateAndTokens(uint256,uint256,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_contracts/0xea58183f57d2f3ee111290164e83d39429b629b1.sol", "function": "addTierRateAndTokens(uint256,uint256,uint256)", "lineno": 392, "title": "Integer Overflow ", "type": "Warning"}, {"address": 13211, "code": " }\n\n ", "debug": "The exception is triggered under the following conditions:\n\nstorage_8: 0x0\nstorage_7: 0x0\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_Target_32_+_36: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_4: 0x0\nstorage_3: 0xffffffffffffffffffffffffffffffffffffffff00\ncaller: 0x0\ncalldata_Target_0: 0x10970fbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_Target: 0x4\nstorage_keccac_storage_7: 0x0\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_contracts/0xea58183f57d2f3ee111290164e83d39429b629b1.sol", "function": "convertTransferredTokensToMny(uint256,address,address,uint256)", "lineno": 385, "title": "Exception state", "type": "Informational"}], "success": true}