{
  "contract": "0x7a18919f0b05fa5e91f3ef43afe8a72105c9d4b8",
  "tool": "mythril",
  "start": 1563499177.9896574,
  "end": 1563499223.4813762,
  "duration": 45.491718769073486,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 2723,
        "code": "b(_value); // Su",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_4: 0x7ffffffffffffffffffffffffffffffffffffffff81fba1cd004cf0000027ffe\nstorage_1 +\nkeccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_4: 0x7fffffffffffffffffffffffffffffff7fffefce006000000018000\ncalldata_WatermelonBlockToken_32 + 36: 0x1fbb1ff006ef0000030000\ntimestamp: 0x0\nstorage_110349606679412691172957834289542550319383271247755660854362242977991410020067: 0x1\nstorage_8: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_2: 0x0\ncalldata_WatermelonBlockToken_4: 0x0\nstorage_0 +\nkeccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_4: 0x1\ncalldata_WatermelonBlockToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_WatermelonBlockToken: 0x4\nstorage_7: 0x0\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/8/0x7a18919f0b05fa5e91f3ef43afe8a72105c9d4b8.sol",
        "function": "transferFrom(address,address,uint256)",
        "lineno": 143,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 5032,
        "code": "\n        retur",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x0\ntimestamp: 0x0\ncalldata_WatermelonBlockToken_32 + 4: 0x1\nstorage_0 +\nkeccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0x1\nstorage_1 +\nkeccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_WatermelonBlockToken_0: 0xa9059cbb00000000000000000000000000000000000000000000000000000000\ncalldatasize_WatermelonBlockToken: 0x4\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/8/0x7a18919f0b05fa5e91f3ef43afe8a72105c9d4b8.sol",
        "function": "transfer(address,uint256)",
        "lineno": 16,
        "title": "Exception state",
        "type": "Informational"
      },
      {
        "address": 5050,
        "code": "t(c>=",
        "debug": "storage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_32_+_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_1 +\nkeccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_4: 0x2\ncalldata_WatermelonBlockToken_32 + 36: 0x80000000040000000000001\ntimestamp: 0x0\nstorage_2: 0x0\ncalldata_WatermelonBlockToken_4: 0x0\nstorage_0 +\nkeccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_4: 0x1\ncalldata_WatermelonBlockToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_WatermelonBlockToken: 0x4\nstorage_8: 0x0\ncallvalue: 0x0\n",
        "description": "A possible integer overflow exists in the function `transferFrom(address,address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.",
        "filename": "/unique_chucks/8/0x7a18919f0b05fa5e91f3ef43afe8a72105c9d4b8.sol",
        "function": "transferFrom(address,address,uint256)",
        "lineno": 22,
        "title": "Integer Overflow ",
        "type": "Warning"
      },
      {
        "address": 5075,
        "code": "\n        return c;\n ",
        "debug": "The exception is triggered under the following conditions:\n\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_4: 0xf39a56ce82c762184002032ea81f083f68302bb22a01ef8bfc2c660300c70b76\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_32_+_4: 0xeb90033f271c11d37dffbc4ff514a79e4582eb21305367e01801000140f9f015\nstorage_1 +\nkeccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_4: 0x4c1c14c85b446facd8016198446138005fcc618024600763a001c6dffffb0b4c\ncalldata_WatermelonBlockToken_32 + 36: 0x26614111e5b30c23917ffff71bada7fe010c232f004160480800000000c89000\ntimestamp: 0x0\nstorage_2: 0x0\ncalldata_WatermelonBlockToken_4: 0x0\nstorage_0 +\nkeccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncalldata_WatermelonBlockToken_4: 0x1\ncalldata_WatermelonBlockToken_0: 0x23b872dd00000000000000000000000000000000000000000000000000000000\ncalldatasize_WatermelonBlockToken: 0x4\nstorage_8: 0x0\ncallvalue: 0x0\n",
        "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ",
        "filename": "/unique_chucks/8/0x7a18919f0b05fa5e91f3ef43afe8a72105c9d4b8.sol",
        "function": "transferFrom(address,address,uint256)",
        "lineno": 22,
        "title": "Exception state",
        "type": "Informational"
      }
    ],
    "success": true
  }
}