2019-08-03 03:33:20,065: [13] m.main:INFO: Registered plugins: DetectUninitializedStorage, DetectEnvInstruction, DetectUnusedRetVal, DetectSuicidal, DetectUninitializedMemory, DetectReentrancyAdvanced, DetectExternalCallAndLeak, DetectIntegerOverflow, DetectReentrancySimple, DetectInvalid, DetectDelegatecall
2019-08-03 03:33:20,065: [13] m.main:INFO: Beginning analysis
2019-08-03 03:33:20,079: [13] m.e.manticore:INFO: Starting symbolic create contract
2019-08-03 03:33:23,610: [13] m.e.manticore:INFO: Starting symbolic transaction: 0
2019-08-03 03:42:42,545: [393] m.c.worker:ERROR: Exception in state 8: AssertionError()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1106, in _checkpoint
    fee = self._calculate_gas(*arguments)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1079, in _calculate_gas
    return current.fee + implementation(*arguments)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1533, in SHA3_gas
    return GSHA3WORD * (ceil32(size) // 32) + memfee
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/expression.py", line 295, in __add__
    return BitVecAdd(self, self.cast(other))
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/expression.py", line 284, in cast
    assert value.size == self.size
AssertionError
 
2019-08-03 03:42:42,759: [13] m.e.manticore:INFO: 1 alive states, 6 terminated states
2019-08-03 03:42:44,825: [13] m.e.manticore:INFO: Starting symbolic transaction: 1
2019-08-03 03:49:14,792: [1939] m.c.worker:ERROR: Exception in state 6: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 972, in _consume
    self.constraints, constraint
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 436, in get_all_values
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-03 03:51:29,719: [1934] m.c.worker:ERROR: Exception in state 5: SolverError('',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/worker.py", line 121, in run
    current_state.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/state.py", line 6, in execute
    return self._platform.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 2684, in execute
    self.current_vm.execute()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1210, in execute
    last_pc, last_gas, instruction, arguments, fee, allocated = self._checkpoint()
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 1109, in _checkpoint
    self._consume(fee)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 952, in _consume
    m = Z3Solver.instance().min(self.constraints, self._gas)
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 118, in min
    return self.optimize(constraints, X, "minimize", M)
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 508, in optimize
    while self._is_sat():
  File "/usr/local/lib/python3.6/dist-packages/manticore/core/smtlib/solver.py", line 328, in _is_sat
    raise SolverError(status)
manticore.exceptions.SolverError
 
2019-08-03 03:51:29,951: [13] m.e.manticore:INFO: 1 alive states, 11 terminated states
2019-08-03 03:51:32,455: [3320] m.c.manticore:INFO: Generated testcase No. 0 - RETURN(1 txs)
2019-08-03 03:51:32,464: [3326] m.c.manticore:INFO: Generated testcase No. 2 - REVERT(2 txs)
2019-08-03 03:51:32,465: [3329] m.c.manticore:INFO: Generated testcase No. 3 - REVERT(2 txs)
2019-08-03 03:51:32,467: [3319] m.c.manticore:INFO: Generated testcase No. 1 - RETURN(3 txs)
2019-08-03 03:51:32,475: [3330] m.c.manticore:INFO: Generated testcase No. 4 - REVERT(2 txs)
2019-08-03 03:51:32,484: [3325] m.c.manticore:INFO: Generated testcase No. 5 - REVERT(2 txs)
2019-08-03 03:51:41,707: [3320] m.c.manticore:INFO: Generated testcase No. 6 - THROW(2 txs)
2019-08-03 03:51:42,125: [3329] m.c.manticore:INFO: Generated testcase No. 7 - RETURN(2 txs)
2019-08-03 03:51:42,630: [3326] m.c.manticore:INFO: Generated testcase No. 8 - REVERT(3 txs)
2019-08-03 03:51:42,817: [3325] m.c.manticore:INFO: Generated testcase No. 9 - REVERT(3 txs)
2019-08-03 03:51:42,835: [3330] m.c.manticore:INFO: Generated testcase No. 10 - REVERT(3 txs)
2019-08-03 03:51:44,275: [3319] m.c.manticore:INFO: Generated testcase No. 11 - REVERT(3 txs)
2019-08-03 03:51:53,100: [3329] m.c.manticore:INFO: Generated testcase No. 12 - RETURN(2 txs)
2019-08-03 03:51:53,212: [3320] m.c.manticore:INFO: Generated testcase No. 13 - RETURN(1 txs)
2019-08-03 03:51:54,035: [3326] m.c.manticore:INFO: Generated testcase No. 14 - RETURN(2 txs)
2019-08-03 03:52:00,075: [13] m.c.manticore:INFO: Results in /mcore_r_hwavow