2019-08-02 20:31:14,165: [12] m.main:INFO: Registered plugins: DetectSuicidal, DetectReentrancySimple, DetectInvalid, DetectEnvInstruction, DetectDelegatecall, DetectUninitializedMemory, DetectReentrancyAdvanced, DetectUnusedRetVal, DetectExternalCallAndLeak, DetectUninitializedStorage, DetectIntegerOverflow
2019-08-02 20:31:14,166: [12] m.main:INFO: Beginning analysis
2019-08-02 20:31:14,173: [12] m.e.manticore:INFO: Starting symbolic create contract
2019-08-02 20:31:15,869: [12] m.e.manticore:INFO: Starting symbolic transaction: 0
2019-08-02 20:31:19,954: [12] m.e.manticore:INFO: 2 alive states, 2 terminated states
2019-08-02 20:31:20,559: [12] m.e.manticore:INFO: Starting symbolic transaction: 1
2019-08-02 20:31:26,469: [12] m.e.manticore:INFO: 4 alive states, 6 terminated states
2019-08-02 20:31:27,263: [2144] m.c.manticore:INFO: Generated testcase No. 0 - RETURN(3 txs)
2019-08-02 20:31:27,297: [2166] m.c.manticore:INFO: Generated testcase No. 5 - RETURN(1 txs)
2019-08-02 20:31:27,297: [2170] m.c.manticore:INFO: Generated testcase No. 4 - REVERT(2 txs)
2019-08-02 20:31:27,301: [2156] m.c.manticore:INFO: Generated testcase No. 3 - RETURN(3 txs)
2019-08-02 20:31:27,315: [2147] m.c.manticore:INFO: Generated testcase No. 1 - RETURN(3 txs)
2019-08-02 20:31:27,327: [2151] m.c.manticore:INFO: Generated testcase No. 2 - RETURN(3 txs)
2019-08-02 20:31:27,328: [2165] m.c.manticore:INFO: Generated testcase No. 6 - RETURN(2 txs)
2019-08-02 20:31:30,436: [2166] m.c.manticore:INFO: Generated testcase No. 7 - RETURN(2 txs)
2019-08-02 20:31:31,245: [2170] m.c.manticore:INFO: Generated testcase No. 8 - REVERT(3 txs)
Process Process-38:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type getTreeSize(Referral.Tree storage)
Process Process-36:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type getTreeSize(Referral.Tree storage)
Process Process-34:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type getTreeSize(Referral.Tree storage)
Process Process-35:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type getReferrer(Referral.Tree storage,address)
Process Process-32:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type getReferrer(Referral.Tree storage,address)
Process Process-41:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type getTreeSize(Referral.Tree storage)
Process Process-39:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type getReferrer(Referral.Tree storage,address)
2019-08-02 20:31:34,175: [12] m.c.manticore:INFO: Results in /mcore_z8rdzrfb
2019-08-02 20:31:35,765: [2644] m.main:INFO: Registered plugins: DetectReentrancySimple, DetectInvalid, DetectUnusedRetVal, DetectUninitializedStorage, DetectIntegerOverflow, DetectSuicidal, DetectExternalCallAndLeak, DetectReentrancyAdvanced, DetectEnvInstruction, DetectUninitializedMemory, DetectDelegatecall
2019-08-02 20:31:35,765: [2644] m.main:INFO: Beginning analysis
2019-08-02 20:31:35,774: [2644] m.e.manticore:INFO: Starting symbolic create contract
2019-08-02 20:31:38,855: [2644] m.e.manticore:INFO: Starting symbolic transaction: 0
2019-08-02 20:31:44,435: [2644] m.e.manticore:INFO: 4 alive states, 2 terminated states
2019-08-02 20:31:45,959: [2644] m.e.manticore:INFO: Starting symbolic transaction: 1
2019-08-02 20:32:02,458: [2644] m.e.manticore:INFO: 16 alive states, 10 terminated states
2019-08-02 20:32:04,393: [6730] m.c.manticore:INFO: Generated testcase No. 0 - RETURN(3 txs)
2019-08-02 20:32:04,399: [6739] m.c.manticore:INFO: Generated testcase No. 2 - RETURN(3 txs)
2019-08-02 20:32:04,401: [6734] m.c.manticore:INFO: Generated testcase No. 1 - RETURN(3 txs)
2019-08-02 20:32:04,425: [6749] m.c.manticore:INFO: Generated testcase No. 3 - RETURN(3 txs)
2019-08-02 20:32:04,487: [6745] m.c.manticore:INFO: Generated testcase No. 4 - RETURN(3 txs)
2019-08-02 20:32:04,683: [6724] m.c.manticore:INFO: Generated testcase No. 6 - RETURN(3 txs)
2019-08-02 20:32:04,720: [6720] m.c.manticore:INFO: Generated testcase No. 5 - RETURN(3 txs)
2019-08-02 20:32:04,882: [6722] m.c.manticore:INFO: Generated testcase No. 7 - RETURN(3 txs)
2019-08-02 20:32:05,018: [6727] m.c.manticore:INFO: Generated testcase No. 8 - RETURN(3 txs)
Process Process-36:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type payoff(Referral.Tree storage,address)
2019-08-02 20:32:20,845: [6734] m.c.manticore:INFO: Generated testcase No. 9 - RETURN(3 txs)
2019-08-02 20:32:21,127: [6739] m.c.manticore:INFO: Generated testcase No. 10 - RETURN(3 txs)
2019-08-02 20:32:21,630: [6745] m.c.manticore:INFO: Generated testcase No. 11 - RETURN(3 txs)
Process Process-34:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type payoff(Referral.Tree storage,address)
2019-08-02 20:32:21,907: [6749] m.c.manticore:INFO: Generated testcase No. 12 - RETURN(3 txs)
Process Process-32:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type payoff(Referral.Tree storage,address)
Process Process-33:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type payoff(Referral.Tree storage,address)
Process Process-35:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type payoff(Referral.Tree storage,address)
Process Process-37:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type payoff(Referral.Tree storage,address)
Process Process-41:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type payoff(Referral.Tree storage,address)
2019-08-02 20:32:28,277: [6745] m.c.manticore:INFO: Generated testcase No. 13 - RETURN(3 txs)
2019-08-02 20:32:28,504: [6739] m.c.manticore:INFO: Generated testcase No. 14 - RETURN(3 txs)
2019-08-02 20:32:32,797: [6745] m.c.manticore:INFO: Generated testcase No. 15 - RETURN(3 txs)
2019-08-02 20:32:33,016: [6739] m.c.manticore:INFO: Generated testcase No. 16 - RETURN(1 txs)
2019-08-02 20:32:36,135: [6739] m.c.manticore:INFO: Generated testcase No. 17 - REVERT(2 txs)
2019-08-02 20:32:37,089: [6745] m.c.manticore:INFO: Generated testcase No. 18 - RETURN(2 txs)
2019-08-02 20:32:39,739: [6739] m.c.manticore:INFO: Generated testcase No. 19 - RETURN(2 txs)
2019-08-02 20:32:41,005: [6745] m.c.manticore:INFO: Generated testcase No. 20 - RETURN(2 txs)
2019-08-02 20:32:43,844: [6739] m.c.manticore:INFO: Generated testcase No. 21 - RETURN(2 txs)
2019-08-02 20:32:45,316: [6745] m.c.manticore:INFO: Generated testcase No. 22 - REVERT(3 txs)
Process Process-38:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type payoff(Referral.Tree storage,address)
2019-08-02 20:32:50,178: [6745] m.c.manticore:INFO: Generated testcase No. 23 - REVERT(3 txs)
2019-08-02 20:32:54,053: [6745] m.c.manticore:INFO: Generated testcase No. 24 - REVERT(3 txs)
2019-08-02 20:32:59,033: [6745] m.c.manticore:INFO: Generated testcase No. 25 - REVERT(3 txs)
Process Process-39:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 212, in deserialize
    result += (ABI._deserialize(abitypes.parse(ty), data[4:]),)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 333, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python3.6/dist-packages/ply/yacc.py", line 1063, in parseopt_notrack
    lookahead = get_token()     # Get the next token
  File "/usr/local/lib/python3.6/dist-packages/ply/lex.py", line 386, in token
    newtok = self.lexerrorf(tok)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abitypes.py", line 144, in t_error
    raise Exception("Illegal character '%s'" % t.value[0])
Exception: Illegal character 'R'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1656, in worker_finalize
    finalizer(q.get_nowait())
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1651, in finalizer
    self.generate_testcase(st, message=message)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/manticore.py", line 1568, in generate_testcase
    is_something_symbolic = sym_tx.dump(tx_summary, state, self, conc_tx=conc_tx)
  File "/usr/local/lib/python3.6/dist-packages/manticore/platforms/evm.py", line 252, in dump
    _, arguments = ABI.deserialize(signature, calldata)
  File "/usr/local/lib/python3.6/dist-packages/manticore/ethereum/abi.py", line 219, in deserialize
    raise EthereumError("Error {} deserializing type {:s}".format(str(e), type_spec))
manticore.exceptions.EthereumError: Error Illegal character 'R' deserializing type payoff(Referral.Tree storage,address)
2019-08-02 20:33:03,269: [2644] m.c.manticore:INFO: Results in /mcore_qvcg7_gr
2019-08-02 20:33:06,168: [7733] m.main:INFO: Registered plugins: DetectReentrancySimple, DetectInvalid, DetectUnusedRetVal, DetectUninitializedStorage, DetectSuicidal, DetectExternalCallAndLeak, DetectEnvInstruction, DetectUninitializedMemory, DetectReentrancyAdvanced, DetectDelegatecall, DetectIntegerOverflow
2019-08-02 20:33:06,168: [7733] m.main:INFO: Beginning analysis
2019-08-02 20:33:06,215: [7733] m.e.manticore:INFO: Starting symbolic create contract
2019-08-02 20:33:06,748: [7777] m.c.manticore:INFO: Generated testcase No. 0 - NO STATE RESULT (?)(0 txs)
2019-08-02 20:33:06,966: [7733] m.c.manticore:INFO: Results in /mcore_6pgakrne
2019-08-02 20:33:07,664: [8036] m.main:INFO: Registered plugins: DetectReentrancySimple, DetectInvalid, DetectSuicidal, DetectReentrancyAdvanced, DetectDelegatecall, DetectExternalCallAndLeak, DetectIntegerOverflow, DetectUninitializedStorage, DetectEnvInstruction, DetectUnusedRetVal, DetectUninitializedMemory
2019-08-02 20:33:07,664: [8036] m.main:INFO: Beginning analysis
2019-08-02 20:33:07,673: [8036] m.e.manticore:INFO: Starting symbolic create contract
2019-08-02 20:33:14,235: [8036] m.e.manticore:INFO: Starting symbolic transaction: 0
2019-08-02 20:34:46,779: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:36:00,023: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:36:29,819: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:36:55,599: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:37:46,890: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:37:50,503: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:39:22,482: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:39:30,794: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:39:49,302: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:40:23,226: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:40:24,586: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:40:35,198: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:40:58,094: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:41:09,613: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:41:15,902: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:41:32,433: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:41:46,509: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:41:49,187: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:42:12,413: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:42:15,378: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:42:24,408: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:42:27,622: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:42:29,722: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:42:44,786: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:42:51,034: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:42:59,334: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:43:33,311: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:43:34,098: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:43:49,990: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:43:50,734: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:43:53,984: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:44:10,627: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:44:20,991: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:44:38,382: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:44:39,086: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:44:40,530: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:44:46,214: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:45:19,382: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:45:23,224: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:45:29,914: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:45:41,490: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:45:44,327: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:46:27,708: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:46:31,895: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:46:38,323: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:46:39,179: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:46:54,303: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:47:04,407: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:47:10,538: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:47:12,031: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:47:31,588: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:47:39,628: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:47:57,314: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:48:04,802: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:48:22,631: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:48:23,299: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:48:32,286: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:48:33,018: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:48:49,730: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:49:06,083: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:49:10,809: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:49:26,591: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:49:45,883: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:49:46,508: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:49:47,827: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:50:10,525: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:50:13,014: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:50:17,320: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:50:19,824: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:50:25,098: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:50:38,298: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:50:41,227: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:51:18,432: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:51:23,721: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:51:41,021: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:51:42,803: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:51:43,098: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:51:43,914: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:52:11,502: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:52:11,520: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:52:14,290: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:52:17,691: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:52:48,398: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:52:55,019: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:52:57,426: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:52:57,928: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:52:58,530: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:53:00,310: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:53:04,691: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:53:05,282: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:53:10,014: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:53:30,082: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:53:42,318: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:53:51,786: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:53:59,623: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:54:20,478: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:54:27,318: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:54:34,591: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:54:45,391: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:55:24,903: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:55:27,713: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:55:30,086: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:55:32,876: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:55:54,588: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:00,107: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:04,909: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:08,996: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:20,586: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:20,982: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:31,490: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:37,714: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:38,613: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:41,817: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:52,725: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:56:58,898: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:57:02,194: [8337] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:57:11,322: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:57:32,421: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:57:34,518: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:57:42,124: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:58:00,475: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:58:00,904: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:58:13,982: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:58:42,885: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:58:52,483: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:58:58,606: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:59:13,003: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:59:26,520: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:59:35,321: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:59:41,194: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:59:42,115: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 20:59:48,222: [8344] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:02,806: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:09,434: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:10,982: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:13,121: [8336] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:13,778: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:15,291: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:27,094: [8334] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:30,179: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:42,790: [8346] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:47,018: [8332] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:49,174: [8341] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:56,421: [8343] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:00:57,387: [8340] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction
2019-08-02 21:01:07,002: [8339] m.e.detectors:WARNING: Unsigned integer overflow at SUB instruction