{"error": null, "issues": [{"address": 5767, "code": " \n/**", "debug": "calldata_UniversalUSD_32 + 4: 0x57f25cd000000000000000000000000000000000000000000000000000000000\nstorage_1: 0xa8795cd3fffffffffffffffffffffffffffffffffffffffffffffffffffffffe\ncalldata_UniversalUSD_4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_3: 0x0\ncaller: 0x0\ncalldata_UniversalUSD_0: 0x40c10f1900000000000000000000000000000000000000000000000000000000\ncalldatasize_UniversalUSD: 0x4\ncallvalue: 0x0\n", "description": "A possible integer overflow exists in the function `mint(address,uint256)`.\nThe addition or multiplication may result in a value higher than the maximum representable integer.", "filename": "/unique_chucks/17/0xd1dfd74c3e4ecd7f798d952715d3cc6ee1c624e9.sol", "function": "mint(address,uint256)", "lineno": 53, "title": "Integer Overflow ", "type": "Warning"}, {"address": 5780, "code": "tle Basic toke", "debug": "The exception is triggered under the following conditions:\n\nstorage_1: 0x1\ncalldata_UniversalUSD_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_UniversalUSD_4: 0xffffffffffffffffffffffffffffffffffffffff\nstorage_3: 0x0\ncaller: 0x0\ncalldata_UniversalUSD_0: 0x40c10f1900000000000000000000000000000000000000000000000000000000\ncalldatasize_UniversalUSD: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/17/0xd1dfd74c3e4ecd7f798d952715d3cc6ee1c624e9.sol", "function": "mint(address,uint256)", "lineno": 55, "title": "Exception state", "type": "Informational"}, {"address": 5803, "code": "\n  /**\n  * @de", "debug": "The exception is triggered under the following conditions:\n\ncalldata_UniversalUSD_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\nstorage_1: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe\nstorage_keccac_1461501637330902918203684832716283019655932542975_&\n1461501637330902918203684832716283019655932542975_&\ncaller: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff\ncalldata_UniversalUSD_0: 0x42966c6800000000000000000000000000000000000000000000000000000000\ncalldatasize_UniversalUSD: 0x4\ncallvalue: 0x0\n", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. ", "filename": "/unique_chucks/17/0xd1dfd74c3e4ecd7f798d952715d3cc6ee1c624e9.sol", "function": "burn(uint256)", "lineno": 43, "title": "Exception state", "type": "Informational"}], "success": true}